site_name: News Signals Datasets
site_url: https://aylien.github.io/news-signals-datasets
nav:
    - Home: index.md
    - signals: api/signals.md
    - signals_dataset: api/signals_dataset.md

plugins: 
  - mkdocstrings

theme: 'material'

extra:
  generator: false